# JWT Configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Access token expiration: 1 hour
application.security.jwt.expiration=3600000
# Refresh token expiration: 7 days
application.security.jwt.refresh-token.expiration=604800000

# Server Configuration
server.port=8080

# Database Configuration
# Add your database configuration here if needed

# Logging Configuration
logging.level.org.springframework.security=DEBUG


# frontend url
app.base-url=http://localhost:3000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=azat.akash@nu.edu.kz
spring.mail.password=Zenbalance123@
spring.mail.protocol=smtp
spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG


# enable authentication and STARTTLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# optional: increase timeouts (in ms)
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
